# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ash/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/221.5080.224/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ash/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/221.5080.224/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ash/Documents/GitHub/personal/drag

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ash/Documents/GitHub/personal/drag

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ash/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/221.5080.224/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ash/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/221.5080.224/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ash/Documents/GitHub/personal/drag/CMakeFiles /home/ash/Documents/GitHub/personal/drag//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ash/Documents/GitHub/personal/drag/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Drag

# Build rule for target.
Drag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Drag
.PHONY : Drag

# fast build rule for target.
Drag/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/build
.PHONY : Drag/fast

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/main.cpp.s
.PHONY : main.cpp.s

src/drag/error/handler.o: src/drag/error/handler.cpp.o
.PHONY : src/drag/error/handler.o

# target to build an object file
src/drag/error/handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/error/handler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/error/handler.cpp.o
.PHONY : src/drag/error/handler.cpp.o

src/drag/error/handler.i: src/drag/error/handler.cpp.i
.PHONY : src/drag/error/handler.i

# target to preprocess a source file
src/drag/error/handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/error/handler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/error/handler.cpp.i
.PHONY : src/drag/error/handler.cpp.i

src/drag/error/handler.s: src/drag/error/handler.cpp.s
.PHONY : src/drag/error/handler.s

# target to generate assembly for a file
src/drag/error/handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/error/handler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/error/handler.cpp.s
.PHONY : src/drag/error/handler.cpp.s

src/drag/exception/drag_exception.o: src/drag/exception/drag_exception.cpp.o
.PHONY : src/drag/exception/drag_exception.o

# target to build an object file
src/drag/exception/drag_exception.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/exception/drag_exception.cpp.o
.PHONY : src/drag/exception/drag_exception.cpp.o

src/drag/exception/drag_exception.i: src/drag/exception/drag_exception.cpp.i
.PHONY : src/drag/exception/drag_exception.i

# target to preprocess a source file
src/drag/exception/drag_exception.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/exception/drag_exception.cpp.i
.PHONY : src/drag/exception/drag_exception.cpp.i

src/drag/exception/drag_exception.s: src/drag/exception/drag_exception.cpp.s
.PHONY : src/drag/exception/drag_exception.s

# target to generate assembly for a file
src/drag/exception/drag_exception.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/exception/drag_exception.cpp.s
.PHONY : src/drag/exception/drag_exception.cpp.s

src/drag/lexer/scanner/scanner.o: src/drag/lexer/scanner/scanner.cpp.o
.PHONY : src/drag/lexer/scanner/scanner.o

# target to build an object file
src/drag/lexer/scanner/scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/scanner/scanner.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/scanner/scanner.cpp.o
.PHONY : src/drag/lexer/scanner/scanner.cpp.o

src/drag/lexer/scanner/scanner.i: src/drag/lexer/scanner/scanner.cpp.i
.PHONY : src/drag/lexer/scanner/scanner.i

# target to preprocess a source file
src/drag/lexer/scanner/scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/scanner/scanner.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/scanner/scanner.cpp.i
.PHONY : src/drag/lexer/scanner/scanner.cpp.i

src/drag/lexer/scanner/scanner.s: src/drag/lexer/scanner/scanner.cpp.s
.PHONY : src/drag/lexer/scanner/scanner.s

# target to generate assembly for a file
src/drag/lexer/scanner/scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/scanner/scanner.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/scanner/scanner.cpp.s
.PHONY : src/drag/lexer/scanner/scanner.cpp.s

src/drag/lexer/token.o: src/drag/lexer/token.cpp.o
.PHONY : src/drag/lexer/token.o

# target to build an object file
src/drag/lexer/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token.cpp.o
.PHONY : src/drag/lexer/token.cpp.o

src/drag/lexer/token.i: src/drag/lexer/token.cpp.i
.PHONY : src/drag/lexer/token.i

# target to preprocess a source file
src/drag/lexer/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token.cpp.i
.PHONY : src/drag/lexer/token.cpp.i

src/drag/lexer/token.s: src/drag/lexer/token.cpp.s
.PHONY : src/drag/lexer/token.s

# target to generate assembly for a file
src/drag/lexer/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token.cpp.s
.PHONY : src/drag/lexer/token.cpp.s

src/drag/lexer/token_literal/base_token.o: src/drag/lexer/token_literal/base_token.cpp.o
.PHONY : src/drag/lexer/token_literal/base_token.o

# target to build an object file
src/drag/lexer/token_literal/base_token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/base_token.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/base_token.cpp.o
.PHONY : src/drag/lexer/token_literal/base_token.cpp.o

src/drag/lexer/token_literal/base_token.i: src/drag/lexer/token_literal/base_token.cpp.i
.PHONY : src/drag/lexer/token_literal/base_token.i

# target to preprocess a source file
src/drag/lexer/token_literal/base_token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/base_token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/base_token.cpp.i
.PHONY : src/drag/lexer/token_literal/base_token.cpp.i

src/drag/lexer/token_literal/base_token.s: src/drag/lexer/token_literal/base_token.cpp.s
.PHONY : src/drag/lexer/token_literal/base_token.s

# target to generate assembly for a file
src/drag/lexer/token_literal/base_token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/base_token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/base_token.cpp.s
.PHONY : src/drag/lexer/token_literal/base_token.cpp.s

src/drag/lexer/token_literal/number_token.o: src/drag/lexer/token_literal/number_token.cpp.o
.PHONY : src/drag/lexer/token_literal/number_token.o

# target to build an object file
src/drag/lexer/token_literal/number_token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/number_token.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/number_token.cpp.o
.PHONY : src/drag/lexer/token_literal/number_token.cpp.o

src/drag/lexer/token_literal/number_token.i: src/drag/lexer/token_literal/number_token.cpp.i
.PHONY : src/drag/lexer/token_literal/number_token.i

# target to preprocess a source file
src/drag/lexer/token_literal/number_token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/number_token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/number_token.cpp.i
.PHONY : src/drag/lexer/token_literal/number_token.cpp.i

src/drag/lexer/token_literal/number_token.s: src/drag/lexer/token_literal/number_token.cpp.s
.PHONY : src/drag/lexer/token_literal/number_token.s

# target to generate assembly for a file
src/drag/lexer/token_literal/number_token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/number_token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/number_token.cpp.s
.PHONY : src/drag/lexer/token_literal/number_token.cpp.s

src/drag/lexer/token_literal/string_token.o: src/drag/lexer/token_literal/string_token.cpp.o
.PHONY : src/drag/lexer/token_literal/string_token.o

# target to build an object file
src/drag/lexer/token_literal/string_token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/string_token.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/string_token.cpp.o
.PHONY : src/drag/lexer/token_literal/string_token.cpp.o

src/drag/lexer/token_literal/string_token.i: src/drag/lexer/token_literal/string_token.cpp.i
.PHONY : src/drag/lexer/token_literal/string_token.i

# target to preprocess a source file
src/drag/lexer/token_literal/string_token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/string_token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/string_token.cpp.i
.PHONY : src/drag/lexer/token_literal/string_token.cpp.i

src/drag/lexer/token_literal/string_token.s: src/drag/lexer/token_literal/string_token.cpp.s
.PHONY : src/drag/lexer/token_literal/string_token.s

# target to generate assembly for a file
src/drag/lexer/token_literal/string_token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_literal/string_token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_literal/string_token.cpp.s
.PHONY : src/drag/lexer/token_literal/string_token.cpp.s

src/drag/lexer/token_type.o: src/drag/lexer/token_type.cpp.o
.PHONY : src/drag/lexer/token_type.o

# target to build an object file
src/drag/lexer/token_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_type.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_type.cpp.o
.PHONY : src/drag/lexer/token_type.cpp.o

src/drag/lexer/token_type.i: src/drag/lexer/token_type.cpp.i
.PHONY : src/drag/lexer/token_type.i

# target to preprocess a source file
src/drag/lexer/token_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_type.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_type.cpp.i
.PHONY : src/drag/lexer/token_type.cpp.i

src/drag/lexer/token_type.s: src/drag/lexer/token_type.cpp.s
.PHONY : src/drag/lexer/token_type.s

# target to generate assembly for a file
src/drag/lexer/token_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/lexer/token_type.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/lexer/token_type.cpp.s
.PHONY : src/drag/lexer/token_type.cpp.s

src/drag/main.o: src/drag/main.cpp.o
.PHONY : src/drag/main.o

# target to build an object file
src/drag/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/main.cpp.o
.PHONY : src/drag/main.cpp.o

src/drag/main.i: src/drag/main.cpp.i
.PHONY : src/drag/main.i

# target to preprocess a source file
src/drag/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/main.cpp.i
.PHONY : src/drag/main.cpp.i

src/drag/main.s: src/drag/main.cpp.s
.PHONY : src/drag/main.s

# target to generate assembly for a file
src/drag/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/main.cpp.s
.PHONY : src/drag/main.cpp.s

src/drag/syntax/ast/parser.o: src/drag/syntax/ast/parser.cpp.o
.PHONY : src/drag/syntax/ast/parser.o

# target to build an object file
src/drag/syntax/ast/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/ast/parser.cpp.o
.PHONY : src/drag/syntax/ast/parser.cpp.o

src/drag/syntax/ast/parser.i: src/drag/syntax/ast/parser.cpp.i
.PHONY : src/drag/syntax/ast/parser.i

# target to preprocess a source file
src/drag/syntax/ast/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/ast/parser.cpp.i
.PHONY : src/drag/syntax/ast/parser.cpp.i

src/drag/syntax/ast/parser.s: src/drag/syntax/ast/parser.cpp.s
.PHONY : src/drag/syntax/ast/parser.s

# target to generate assembly for a file
src/drag/syntax/ast/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/ast/parser.cpp.s
.PHONY : src/drag/syntax/ast/parser.cpp.s

src/drag/syntax/expr/binary.o: src/drag/syntax/expr/binary.cpp.o
.PHONY : src/drag/syntax/expr/binary.o

# target to build an object file
src/drag/syntax/expr/binary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/binary.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/syntax/expr/binary.cpp.o
.PHONY : src/drag/syntax/expr/binary.cpp.o

src/drag/syntax/expr/binary.i: src/drag/syntax/expr/binary.cpp.i
.PHONY : src/drag/syntax/expr/binary.i

# target to preprocess a source file
src/drag/syntax/expr/binary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/binary.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/syntax/expr/binary.cpp.i
.PHONY : src/drag/syntax/expr/binary.cpp.i

src/drag/syntax/expr/binary.s: src/drag/syntax/expr/binary.cpp.s
.PHONY : src/drag/syntax/expr/binary.s

# target to generate assembly for a file
src/drag/syntax/expr/binary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/binary.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/syntax/expr/binary.cpp.s
.PHONY : src/drag/syntax/expr/binary.cpp.s

src/drag/syntax/expr/grouping.o: src/drag/syntax/expr/grouping.cpp.o
.PHONY : src/drag/syntax/expr/grouping.o

# target to build an object file
src/drag/syntax/expr/grouping.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/grouping.cpp.o
.PHONY : src/drag/syntax/expr/grouping.cpp.o

src/drag/syntax/expr/grouping.i: src/drag/syntax/expr/grouping.cpp.i
.PHONY : src/drag/syntax/expr/grouping.i

# target to preprocess a source file
src/drag/syntax/expr/grouping.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/grouping.cpp.i
.PHONY : src/drag/syntax/expr/grouping.cpp.i

src/drag/syntax/expr/grouping.s: src/drag/syntax/expr/grouping.cpp.s
.PHONY : src/drag/syntax/expr/grouping.s

# target to generate assembly for a file
src/drag/syntax/expr/grouping.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/grouping.cpp.s
.PHONY : src/drag/syntax/expr/grouping.cpp.s

src/drag/syntax/expr/literal.o: src/drag/syntax/expr/literal.cpp.o
.PHONY : src/drag/syntax/expr/literal.o

# target to build an object file
src/drag/syntax/expr/literal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/literal.cpp.o
.PHONY : src/drag/syntax/expr/literal.cpp.o

src/drag/syntax/expr/literal.i: src/drag/syntax/expr/literal.cpp.i
.PHONY : src/drag/syntax/expr/literal.i

# target to preprocess a source file
src/drag/syntax/expr/literal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/literal.cpp.i
.PHONY : src/drag/syntax/expr/literal.cpp.i

src/drag/syntax/expr/literal.s: src/drag/syntax/expr/literal.cpp.s
.PHONY : src/drag/syntax/expr/literal.s

# target to generate assembly for a file
src/drag/syntax/expr/literal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/literal.cpp.s
.PHONY : src/drag/syntax/expr/literal.cpp.s

src/drag/syntax/expr/unary.o: src/drag/syntax/expr/unary.cpp.o
.PHONY : src/drag/syntax/expr/unary.o

# target to build an object file
src/drag/syntax/expr/unary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/unary.cpp.o
.PHONY : src/drag/syntax/expr/unary.cpp.o

src/drag/syntax/expr/unary.i: src/drag/syntax/expr/unary.cpp.i
.PHONY : src/drag/syntax/expr/unary.i

# target to preprocess a source file
src/drag/syntax/expr/unary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/unary.cpp.i
.PHONY : src/drag/syntax/expr/unary.cpp.i

src/drag/syntax/expr/unary.s: src/drag/syntax/expr/unary.cpp.s
.PHONY : src/drag/syntax/expr/unary.s

# target to generate assembly for a file
src/drag/syntax/expr/unary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/unary.cpp.s
.PHONY : src/drag/syntax/expr/unary.cpp.s

src/drag/syntax/expr/visitors/visitor.o: src/drag/syntax/expr/visitors/visitor.cpp.o
.PHONY : src/drag/syntax/expr/visitors/visitor.o

# target to build an object file
src/drag/syntax/expr/visitors/visitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/visitors/visitor.cpp.o
.PHONY : src/drag/syntax/expr/visitors/visitor.cpp.o

src/drag/syntax/expr/visitors/visitor.i: src/drag/syntax/expr/visitors/visitor.cpp.i
.PHONY : src/drag/syntax/expr/visitors/visitor.i

# target to preprocess a source file
src/drag/syntax/expr/visitors/visitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/visitors/visitor.cpp.i
.PHONY : src/drag/syntax/expr/visitors/visitor.cpp.i

src/drag/syntax/expr/visitors/visitor.s: src/drag/syntax/expr/visitors/visitor.cpp.s
.PHONY : src/drag/syntax/expr/visitors/visitor.s

# target to generate assembly for a file
src/drag/syntax/expr/visitors/visitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/syntax/expr/visitors/visitor.cpp.s
.PHONY : src/drag/syntax/expr/visitors/visitor.cpp.s

src/drag/util/file_manipulator.o: src/drag/util/file_manipulator.cpp.o
.PHONY : src/drag/util/file_manipulator.o

# target to build an object file
src/drag/util/file_manipulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/file_manipulator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/file_manipulator.cpp.o
.PHONY : src/drag/util/file_manipulator.cpp.o

src/drag/util/file_manipulator.i: src/drag/util/file_manipulator.cpp.i
.PHONY : src/drag/util/file_manipulator.i

# target to preprocess a source file
src/drag/util/file_manipulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/file_manipulator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/file_manipulator.cpp.i
.PHONY : src/drag/util/file_manipulator.cpp.i

src/drag/util/file_manipulator.s: src/drag/util/file_manipulator.cpp.s
.PHONY : src/drag/util/file_manipulator.s

# target to generate assembly for a file
src/drag/util/file_manipulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/file_manipulator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/file_manipulator.cpp.s
.PHONY : src/drag/util/file_manipulator.cpp.s

src/drag/util/iterator.o: src/drag/util/iterator.cpp.o
.PHONY : src/drag/util/iterator.o

# target to build an object file
src/drag/util/iterator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/iterator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/iterator.cpp.o
.PHONY : src/drag/util/iterator.cpp.o

src/drag/util/iterator.i: src/drag/util/iterator.cpp.i
.PHONY : src/drag/util/iterator.i

# target to preprocess a source file
src/drag/util/iterator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/iterator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/iterator.cpp.i
.PHONY : src/drag/util/iterator.cpp.i

src/drag/util/iterator.s: src/drag/util/iterator.cpp.s
.PHONY : src/drag/util/iterator.s

# target to generate assembly for a file
src/drag/util/iterator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/iterator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/iterator.cpp.s
.PHONY : src/drag/util/iterator.cpp.s

src/drag/util/string_object.o: src/drag/util/string_object.cpp.o
.PHONY : src/drag/util/string_object.o

# target to build an object file
src/drag/util/string_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/string_object.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/string_object.cpp.o
.PHONY : src/drag/util/string_object.cpp.o

src/drag/util/string_object.i: src/drag/util/string_object.cpp.i
.PHONY : src/drag/util/string_object.i

# target to preprocess a source file
src/drag/util/string_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/string_object.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/string_object.cpp.i
.PHONY : src/drag/util/string_object.cpp.i

src/drag/util/string_object.s: src/drag/util/string_object.cpp.s
.PHONY : src/drag/util/string_object.s

# target to generate assembly for a file
src/drag/util/string_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/string_object.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/string_object.cpp.s
.PHONY : src/drag/util/string_object.cpp.s

src/drag/util/type_mapper.o: src/drag/util/type_mapper.cpp.o
.PHONY : src/drag/util/type_mapper.o

# target to build an object file
src/drag/util/type_mapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/type_mapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/type_mapper.cpp.o
.PHONY : src/drag/util/type_mapper.cpp.o

src/drag/util/type_mapper.i: src/drag/util/type_mapper.cpp.i
.PHONY : src/drag/util/type_mapper.i

# target to preprocess a source file
src/drag/util/type_mapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/type_mapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/type_mapper.cpp.i
.PHONY : src/drag/util/type_mapper.cpp.i

src/drag/util/type_mapper.s: src/drag/util/type_mapper.cpp.s
.PHONY : src/drag/util/type_mapper.s

# target to generate assembly for a file
src/drag/util/type_mapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Drag.dir/build.make CMakeFiles/Drag.dir/src/drag/util/type_mapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/src/drag/util/type_mapper.cpp.s
.PHONY : src/drag/util/type_mapper.cpp.s

test/test_cases/file_manipulator_test.o: test/test_cases/file_manipulator_test.cpp.o
.PHONY : test/test_cases/file_manipulator_test.o

# target to build an object file
test/test_cases/file_manipulator_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test_cases/file_manipulator_test.cpp.o
.PHONY : test/test_cases/file_manipulator_test.cpp.o

test/test_cases/file_manipulator_test.i: test/test_cases/file_manipulator_test.cpp.i
.PHONY : test/test_cases/file_manipulator_test.i

# target to preprocess a source file
test/test_cases/file_manipulator_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test_cases/file_manipulator_test.cpp.i
.PHONY : test/test_cases/file_manipulator_test.cpp.i

test/test_cases/file_manipulator_test.s: test/test_cases/file_manipulator_test.cpp.s
.PHONY : test/test_cases/file_manipulator_test.s

# target to generate assembly for a file
test/test_cases/file_manipulator_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test_cases/file_manipulator_test.cpp.s
.PHONY : test/test_cases/file_manipulator_test.cpp.s

test/test_cases/token_type_test.o: test/test_cases/token_type_test.cpp.o
.PHONY : test/test_cases/token_type_test.o

# target to build an object file
test/test_cases/token_type_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test_cases/token_type_test.cpp.o
.PHONY : test/test_cases/token_type_test.cpp.o

test/test_cases/token_type_test.i: test/test_cases/token_type_test.cpp.i
.PHONY : test/test_cases/token_type_test.i

# target to preprocess a source file
test/test_cases/token_type_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test_cases/token_type_test.cpp.i
.PHONY : test/test_cases/token_type_test.cpp.i

test/test_cases/token_type_test.s: test/test_cases/token_type_test.cpp.s
.PHONY : test/test_cases/token_type_test.s

# target to generate assembly for a file
test/test_cases/token_type_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/test_cases/token_type_test.cpp.s
.PHONY : test/test_cases/token_type_test.cpp.s

test/unit_test.o: test/unit_test.cpp.o
.PHONY : test/unit_test.o

# target to build an object file
test/unit_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/unit_test.cpp.o
.PHONY : test/unit_test.cpp.o

test/unit_test.i: test/unit_test.cpp.i
.PHONY : test/unit_test.i

# target to preprocess a source file
test/unit_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/unit_test.cpp.i
.PHONY : test/unit_test.cpp.i

test/unit_test.s: test/unit_test.cpp.s
.PHONY : test/unit_test.s

# target to generate assembly for a file
test/unit_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/test/unit_test.cpp.s
.PHONY : test/unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Drag"
	@echo "... Test"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/drag/error/handler.o"
	@echo "... src/drag/error/handler.i"
	@echo "... src/drag/error/handler.s"
	@echo "... src/drag/exception/drag_exception.o"
	@echo "... src/drag/exception/drag_exception.i"
	@echo "... src/drag/exception/drag_exception.s"
	@echo "... src/drag/lexer/scanner/scanner.o"
	@echo "... src/drag/lexer/scanner/scanner.i"
	@echo "... src/drag/lexer/scanner/scanner.s"
	@echo "... src/drag/lexer/token.o"
	@echo "... src/drag/lexer/token.i"
	@echo "... src/drag/lexer/token.s"
	@echo "... src/drag/lexer/token_literal/base_token.o"
	@echo "... src/drag/lexer/token_literal/base_token.i"
	@echo "... src/drag/lexer/token_literal/base_token.s"
	@echo "... src/drag/lexer/token_literal/number_token.o"
	@echo "... src/drag/lexer/token_literal/number_token.i"
	@echo "... src/drag/lexer/token_literal/number_token.s"
	@echo "... src/drag/lexer/token_literal/string_token.o"
	@echo "... src/drag/lexer/token_literal/string_token.i"
	@echo "... src/drag/lexer/token_literal/string_token.s"
	@echo "... src/drag/lexer/token_type.o"
	@echo "... src/drag/lexer/token_type.i"
	@echo "... src/drag/lexer/token_type.s"
	@echo "... src/drag/main.o"
	@echo "... src/drag/main.i"
	@echo "... src/drag/main.s"
	@echo "... src/drag/syntax/ast/parser.o"
	@echo "... src/drag/syntax/ast/parser.i"
	@echo "... src/drag/syntax/ast/parser.s"
	@echo "... src/drag/syntax/expr/binary.o"
	@echo "... src/drag/syntax/expr/binary.i"
	@echo "... src/drag/syntax/expr/binary.s"
	@echo "... src/drag/syntax/expr/grouping.o"
	@echo "... src/drag/syntax/expr/grouping.i"
	@echo "... src/drag/syntax/expr/grouping.s"
	@echo "... src/drag/syntax/expr/literal.o"
	@echo "... src/drag/syntax/expr/literal.i"
	@echo "... src/drag/syntax/expr/literal.s"
	@echo "... src/drag/syntax/expr/unary.o"
	@echo "... src/drag/syntax/expr/unary.i"
	@echo "... src/drag/syntax/expr/unary.s"
	@echo "... src/drag/syntax/expr/visitors/visitor.o"
	@echo "... src/drag/syntax/expr/visitors/visitor.i"
	@echo "... src/drag/syntax/expr/visitors/visitor.s"
	@echo "... src/drag/util/file_manipulator.o"
	@echo "... src/drag/util/file_manipulator.i"
	@echo "... src/drag/util/file_manipulator.s"
	@echo "... src/drag/util/iterator.o"
	@echo "... src/drag/util/iterator.i"
	@echo "... src/drag/util/iterator.s"
	@echo "... src/drag/util/string_object.o"
	@echo "... src/drag/util/string_object.i"
	@echo "... src/drag/util/string_object.s"
	@echo "... src/drag/util/type_mapper.o"
	@echo "... src/drag/util/type_mapper.i"
	@echo "... src/drag/util/type_mapper.s"
	@echo "... test/test_cases/file_manipulator_test.o"
	@echo "... test/test_cases/file_manipulator_test.i"
	@echo "... test/test_cases/file_manipulator_test.s"
	@echo "... test/test_cases/token_type_test.o"
	@echo "... test/test_cases/token_type_test.i"
	@echo "... test/test_cases/token_type_test.s"
	@echo "... test/unit_test.o"
	@echo "... test/unit_test.i"
	@echo "... test/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

