name: Main Workflow Runner
on:
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test_mac:
    name: Unit Tests For macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Run Test